Pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),
    path('pp/', include(('pp.urls', 'pp'), namespace='pp')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.GetCartView.as_view(), name='view_cart'),
    path('update/<int:product_id>', views.ChangeQuantityView.as_view(), name='update_quantity'),
    path('check/', views.AcceptOrderView.as_view(), name='accept_order'),
    path('history/', views.GetHistoryView.as_view(), name='order'),
    path('remove/<int:product_id>', views.RemoveFromCartView.as_view(), name='remove'),
]

pp/urls.py
from django.urls import path

from pp import views

urlpatterns = [
    path('', views.ListPizza.as_view(), name='index'),
    path('create/', views.CreatePizza.as_view(), name='create_pizza'),
    path('<slug:slug>/', views.ViewPizza.as_view(), name='pizza'),
]

cart/models.py
from django.db import models
from pp.models import Pizza
from accounts.models import User


class History(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    # title + amount затем функция преобразует во вложенные списки
    pizza_list = models.CharField(max_length=400)

    total_cart_price = models.CharField(max_length=20, default=0)
    address = models.CharField(max_length=150, default='kek')

    created_at = models.DateTimeField(auto_now_add=True)

    def __iter__(self):
        for item in History.objects.all():
            yield item

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

cart/forms.py
from django import forms
from accounts.models import User
from django.core.exceptions import ValidationError


class PizzaForm(forms.Form):
    quantity = forms.CharField()
    quantity.widget = forms.TextInput(attrs={'class': 'form-control'})

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']

        chars = '0123456789'
        for i in quantity:
            if i not in chars:
                raise ValidationError('Price must contain only numeric characters.')

        if len(quantity) > 2:
            raise ValidationError('Too big quantity.')

        return quantity


class UserForm(forms.ModelForm):
    class Meta:
        model = User

        fields = ['phone_num', 'address']

        widgets = {
            'phone_num': forms.TextInput(attrs={'class': 'form-control'}),
            'address': forms.TextInput(attrs={'class': 'form-control'}),
        }

cart/views.py
from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404, Http404
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from cart.cart import Cart, get_cart_len
from pp.models import Pizza
from .models import History
from .forms import *
from .custom_modul import *
from .email import email


class AddToCartView(View):
    @staticmethod
    def post(request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Pizza, id=product_id)
        cart.add(product=product)

        return redirect('cart:view_cart')


class ChangeQuantityView(View):
    @staticmethod
    def post(request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Pizza, id=product_id)
        form = PizzaForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            cart.add(product=product, quantity=cd['quantity'])

        return redirect('cart:view_cart')


class AcceptOrderView(View):
    @staticmethod
    def post(request):
        form = UserForm(data=request.POST, instance=request.user)

        if form.is_valid():
            form.save()

        cart = Cart(request)
        pizza_list = create_info_for_history(cart)
        total_cart_price = cart.get_total_cart_price()

        his = History(user=request.user,
                      pizza_list=pizza_list,
                      address=request.user.address,
                      total_cart_price=total_cart_price
                      )

        history_list = his.pizza_list.split('\n\n')[:-1]
        pizza_list = list()

        for item in history_list:
            pizza_list.append(item.split('\n'))

        total_cart_price = cart.get_total_cart_price()

        if not email(request, his):
            return redirect('cart:view_cart')

        his.save()
        cart.clear()

        return render(request, 'cart/checklist.html',
                      context={'history': his,
                               'pizza_list': pizza_list,
                               'total_cart_price': total_cart_price}
                      )


class GetHistoryView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        try:
            his = get_list_or_404(History.objects.all().order_by('-created_at'), user=request.user)
        except Http404:
            his = list()

        member_list = list()

        if his:
            """if history is not empty, collect and prepare history members"""
            for member in his:
                pizza_list = list()
                tmp = member.pizza_list.split('\n\n')[:-1]  # -1, because last member is ''
                for i in tmp:
                    pizza_list.append(i.split('\n'))

                member_list.append(HistoryInfo(
                            pizza_list,
                            member.total_cart_price,
                            member.address,
                            member.created_at
                        ))

            return render(request, 'cart/history.html',
                          context={'member_list': member_list,
                                   'cart_len': get_cart_len(request)
                                   }
                          )

        return render(request,
                      'cart/history.html',
                      context={'member_list': False,
                               'cart_len': get_cart_len(request)
                               }
                      )


class GetCartView(LoginRequiredMixin, View):
    @staticmethod
    def get(request):
        cart = Cart(request)
        user = request.user

        for item in cart:
            item['pizza_form'] = PizzaForm(initial={'quantity': item['quantity']})

        user_form = UserForm(initial={'phone_num': user.phone_num, 'address': user.address})

        return render(request,
                      'cart/view_cart.html',
                      context={'cart': cart,
                               'user_form': user_form,
                               'cart_len': get_cart_len(request)
                               }
                      )


class RemoveFromCartView(View):
    @staticmethod
    def post(request, product_id):
        cart = Cart(request)
        product = get_object_or_404(Pizza, id=product_id)
        cart.remove(product)

        return redirect('cart:view_cart')

cart/templates/cart/checklist.html
{% extends 'pp/base.html' %}
{% load static %}

{% block title %}
    Check - {{ block.super }}
{% endblock %}

{% block body %}
    <p>Name: {{ history.user.get_full_name}}</p> <br>
    {% for item in pizza_list %}
        {% for i in item %}
            {{ i }} <br>
        {% endfor %} <br>
    {% endfor %} <br>
    <p>Total Price: {{ total_cart_price }}$</p>
    <p>Address: {{ history.user.address }}</p>
    <p>Date: {{ history.created_at }}</p>
    <form action="{% url "pp:index" %}">
        <input type="submit" class="btn btn-dark" value="Continue" value="Continue">
    </form> <br>
{% endblock %}

cart/templates/cart/history.html
{% extends 'pp/base.html' %}
{% load static %}

{% block title %}
    History - {{ block.super }}
{% endblock %}

{% block body %}
    {% if member_list %}
        {% for item in member_list %}
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle history" type="button" id="dropdownMenu2"
                        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    {{ item.created_at }}
                </button>
                <div class="dropdown-menu dropdown-menu-right history" aria-labelledby="dropdownMenu2">
                    {% for row in item.pizza_list %}
                        {% for part in row %}
                            {{ part }} <br>
                        {% endfor %} <br>
                    {% endfor %}
                    Total Price: {{ item.total_cart_price }}$ <br>
                    Address: {{ item.address }}
                </div>
            </div> <br>
        {% endfor %}
    {% else %}
        You purchase History is Empty.
    {% endif %}
    <form action="{% url "pp:index" %}">
        <input type="submit" class="btn btn-dark" value="Continue">
    </form> <br>
{% endblock %}

cart/templates/cart/view_cart.html
{% extends 'pp/base.html' %}
{% load static %}
{% load image_filters %}

{% block title %}
    Cart - {{ block.super }}
{% endblock %}


{% block body %}
    <div class="row row-cols-1 row-cols-md-3">
        {% for item in cart %}
            <div class="col mb-4">
                <div class="card h-100 cart_card">
                    {% with product=item.product %}
                        <div class="cart_title left_five_px">Pizza: {{ product.title }}</div>
                        <div class="left_five_px">Price: {{ product.price }}$</div>
                        {% if item.image|is_exists %}
                            <img src="{{ item.image.read|make_src }}" class="cart_img card-img-top main-content">
                        {% else %}
                            <img src="{% static 'pp/image/not_found.png' %}" class="cart_img card-img-top main-content">
                        {% endif %}
                    {% endwith %}

                    <form action="{% url "cart:update_quantity" item.product.id %}" method="post">
                        {% csrf_token %}
                        <p class="cart_item_q left_five_px">Quantity {{ item.pizza_form.quantity }}</p>
                    </form>

                    <div>
                        <div class="cart_item_tp left_five_px" style="display: inline-block;">
                            Sum: {{ item.total_price }}$
                        </div>
                        <div class="cart_rm_div" style="display: inline-block;">
                            <form action="{% url "cart:remove" item.product.id %}" method="post" class="cart_rm_form">
                                {% csrf_token %}
                                <input type="submit" class="btn btn-danger" value="Remove">
                            </form>
                        </div>
                    </div>

                </div>
            </div>
        {% endfor %}
    </div>
    <form action="{% url "cart:accept_order" %}" method="post" style="margin-left: 20%">
        {% csrf_token %}
        <div style="width: 900px;">
            <div style="display: inline-block">
                Phone Number: {{ user_form.phone_num }}
            </div>
            <div style="width: 400px; display: inline-block">
                Address: {{ user_form.address }}
            </div>
            <div style="display: inline-block">
                {% if cart %}
                    <input name="total_price" type="submit" class="btn btn-primary" value="{{ cart.get_total_cart_price }}$"
                           style="width: 120px;">
                {% endif %}
            </div>
        </div>
    </form> <br>
{% endblock %}