Pizza/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html')),
    path('pp/', include(('pp.urls', 'pp'), namespace='pp')),
    path('', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('', include(('cart.urls', 'cart'), namespace='cart')),
    path('api/', include(('api.urls', 'api'), namespace='api')),
]

accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from accounts import views

urlpatterns = [
    path('login/', views.PizzaLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', views.PizzaUserCreationView.as_view(), name='register')
]

cart/urls.py
from django.urls import path

from cart import views

urlpatterns = [
    path('add/<int:product_id>/', views.AddToCartView.as_view(), name='add_to_cart'),
    path('cart/', views.GetCartView.as_view(), name='view_cart'),
    path('update/<int:product_id>', views.ChangeQuantityView.as_view(), name='update_quantity'),
    path('check/', views.AcceptOrderView.as_view(), name='accept_order'),
    path('history/', views.GetHistoryView.as_view(), name='order'),
    path('remove/<int:product_id>', views.RemoveFromCartView.as_view(), name='remove'),
]

pp/urls.py
from django.urls import path

from pp import views

urlpatterns = [
    path('', views.ListPizza.as_view(), name='index'),
    path('create/', views.CreatePizza.as_view(), name='create_pizza'),
    path('<slug:slug>/', views.ViewPizza.as_view(), name='pizza'),
]

pp/models.py
from time import time
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from os.path import join, dirname, basename
from random import randint
import transliterate


class Post(models.Model):
    title = models.CharField(max_length=256, db_index=True)
    slug = models.SlugField(unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

    def custom_save(self, *args, **kwargs):
        """used by fill_menu, if names contains rus chars"""
        title = transliterate.translit(self.title.lower(), reversed=True)
        self.slug = slugify(title.replace(' ', '_').replace('-', '_')) + str(int(time()) + randint(1, 100))

        super().save(*args, **kwargs)

    def save(self, *args, **kwargs):
        """base save"""
        if not self.slug:
            self.slug = slugify(self.title.lower().replace(' ', '_').replace('-', '_')) + str(
                int(time()) + randint(1, 100))

        super().save(*args, **kwargs)

    def __str__(self):
        return f'<{self.__class__.__name__}:{self.title}>'

    @staticmethod
    def upload_to(instance, filename):
        return join(
            dirname(basename(__file__)), instance.__class__.__name__, filename
        )


class Pizza(Post):
    body = models.TextField(blank=True, db_index=True)
    price = models.TextField(blank=True, default=None)
    image = models.ImageField(default=None, upload_to=Post.upload_to)

    def get_absolute_url(self):
        return reverse('pp:pizza', kwargs={'slug': self.slug})

pp/forms.py
from django import forms
from django.core.exceptions import ValidationError

from pp.models import Pizza


class PizzaForm(forms.ModelForm):
    class Meta:
        model = Pizza
        fields = ['title', 'body', 'price', 'image']

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'body': forms.Textarea(attrs={'class': 'form-control'}),
            'price': forms.TextInput(attrs={'class': 'form-control'}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control'})
        }

    def clean_price(self):
        price = self.cleaned_data['price']

        chars = ',.0123456789'
        for i in price:
            if i not in chars:
                raise ValidationError('Price must contain only numeric characters.')

        if ',' in price:
            price = price.replace(',', '.')

        if '.' not in price:
            price += '.0'

        return price

pp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.views import View

from pp.forms import PizzaForm
from pp.mixins import ListObjectsMixin
from cart.cart import get_cart_len
from pp.models import Pizza


class ListPizza(ListObjectsMixin, View):
    model = Pizza
    template_name = 'pp/index.html'
    template_include = 'pp/includes/pizz.html'


class ViewPizza(View):
    @staticmethod
    def get(request, slug):
        pizza = get_object_or_404(Pizza, slug=slug)
        return render(
            request,
            'pp/one_pizza.html',
            context={
                'pizza': pizza,
                'cart_len': get_cart_len(request)
            }
        )


class CreatePizza(LoginRequiredMixin, View):
    raise_exception = True

    @staticmethod
    def get(request):
        user = request.user

        if user.is_staff:
            form = PizzaForm()

            return render(
                request,
                'pp/create_pizza.html',
                context={
                    'form': form,
                    'cart_len': get_cart_len(request)
                }
            )

        return redirect('pp:index')

    @staticmethod
    def post(request):
        user = request.user

        if user.is_staff:
            form = PizzaForm(request.POST, request.FILES)

            if form.is_valid():
                pizza = form.save()
                pizza.save()

                return redirect(pizza)

            return render(
                request,
                'pp/create_pizza.html',
                context={
                    'form': form,
                    'cart_len': get_cart_len(request)
                }
            )

        return redirect('pp:index')

pp/templates/pp/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'pp:index' %}">Pizza</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            {% if user.is_staff %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'pp:create_pizza' %}">Create<span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin<span class="sr-only">(current)</span></a>
                </li>
            {% endif %}
            {% if user.is_authenticated %}
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'cart:order' %}" id="his">History<span class="sr-only">(current)</span></a>
                </li>
                <div style="width: 100px;">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'cart:view_cart' %}">Cart {% if cart_len %}({{ cart_len }})
                        {% endif %}<span class="sr-only">(current)</span></a>
                    </li>
                </div>
            {% endif %}
        </ul>
        <form class="form-inline my-2 my-lg-0 search-field" method="get">
            <input name="search" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search"
                   value="{{ request.GET.search }}">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
        {% if not user.is_authenticated %}
            <div>
                <button class="btn btn-outline-success my-2 my-sm-0" type="button" data-toggle="modal"
                        data-target="#loginModal" name="login">Login
                </button>
                {% include 'accounts/includes/modal.html' with type='login' %}
                <button class="btn btn-outline-warning my-2 my-sm-0" type="button" data-toggle="modal"
                        data-target="#registerModal">Register
                </button>
                {% include 'accounts/includes/modal.html' with type='register' %}
            </div>
        {% else %}
            <ul class="navbar-nav">
                <li class="nav-item active user-info">
                    {{ user.first_name }}
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'accounts:logout' %}" method="post">
                {% csrf_token %}
                <button name="logout" class="btn btn-outline-danger my-2 my-sm-0" type="submit">Logout</button>
            </form>
        {% endif %}
    </div>
</nav>

pp/templates/pp/includes/pizz.html
{% load image_filters %}
{% load static %}


{% for pizza in objects %}
    <div class="col mb-4">
        <div class="card card_hover text-white bg-dark">
            {% if pizza.image|is_exists %}
                <a href="{{ pizza.get_absolute_url }}">
                    <img src="{{ pizza.image.read|make_src }}" class="card-img-top main-content">
                </a>
            {% else %}
                <a href="{{ pizza.get_absolute_url }}">
                    <img src="{% static 'pp/image/not_found.png' %}" class="card-img-top main-content">
                </a>
            {% endif %}
            <div class="card-body">
                <h5 class="card-title" align="center">{{ pizza.title|truncatechars:20 }}</h5>
                {% if user.is_authenticated %}
                    <form action="{% url 'cart:add_to_cart' pizza.id %}" method="post">
                        {% csrf_token %}
                        <input name="price" type="submit" class="add_btn btn btn-outline-success" value="{{ pizza.price }}$">
                    </form>
                {% else %}
                    <input type="submit" class="add_btn btn btn-outline-success" value="{{ pizza.price }}$">
                {% endif %}
            </div>
        </div>
    </div>
{% endfor %}